import Head from "next/head";
import Dashboard from "./../components/dashboard/Dashboard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-16">
        <h1>Main Home Page</h1>
      </main>
    </div>
  );
}
